

name: var experiment

on:
  workflow_dispatch:
    inputs:
      var:
        description: 'Description for var'
        required: false
        default: 'false'
        
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Check if not triggered by workflow dispatch set to default
      id: updated_input
      run: |
        if [[ ${{ github.event_name }} != 'workflow_dispatch' ]]; then
          echo "This workflow was not triggered by workflow_dispatch"
          echo "VERSION_FLAG=false" >> "$GITHUB_OUTPUT"
        else
          echo "This workflow was triggered by workflow_dispatch"
          echo "VERSION_FLAG=${{ inputs.isMajorVersion }}" >> "$GITHUB_OUTPUT"
        fi
    - name: Check if not triggered by workflow_dispatch set false
      uses: actions/checkout@v4
      
