name: publish-release
permissions:
  contents: write
  pull-requests: read
'on':
  workflow_dispatch:
    inputs:
      isMajorVersion:
        type: boolean
        description: Breaks Backwards Compatibility
        default: false
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  setup-vars:
    runs-on: ubuntu-latest
    steps:
    - name: Check if not triggered by workflow dispatch set to default
      id: updated_input
      run: |
        echo ${{ inputs.isMajorVersion }}
        echo "FLAG = ${{ inputs.isMajorVersion }}"
        echo ${{inputs.isMajorVersion}}
        echo "WS ${{inputs.isMajorVersion}}"
        echo $inputs.isMajorVersion

        echo "EVENT:  ${{ github.event_name }}"
        if [[ ${{ github.event_name }} != 'workflow_dispatch' ]]; then
          echo "VERSION_FLAG=false" >> "$GITHUB_OUTPUT"
        else
          echo "This workflow was triggered by workflow_dispatch"
          echo "VERSION_FLAG=${{ inputs.isMajorVersion }}" >> "$GITHUB_OUTPUT"
        fi     
  publis-release:
    runs-on: ubuntu-latest
    needs: setup-vars
    steps:
      - name: test
        run: |
          echo ${{needs.setup-vars.outputs.VERSION_FLAG}}
