name: Update Input Variable

on:
 workflow_dispatch:
  inputs:
    is_ver: 
      type: boolean
      default: false
 push:
    branches:
      - main
      - master
env:
  var1: false
  type: boolean

jobs:
  update_variable:
    runs-on: ubuntu-latest
    env:
      MY_VARIABLE: initial_value
    steps:
      - name: Update Variable
        run: echo "::set-env name=MY_VARIABLE::new_value"

      - name: Use Updated Variable
        run: |
          echo "Updated value is $MY_VARIABLE"
          echo "Updated value is ${{ inputs.var }}"       
          echo "Updated value is ${{ inputs.var1 }}"       
