name: publish-release
permissions:
  contents: write
  pull-requests: read
'on':
  workflow_dispatch:
    inputs:
      isMajorVersion:
        type: boolean
        description: Breaks Backwards Compatibility
        default: false
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  setup-vars:
    runs-on: ubuntu-latest
    steps:
    - name: Check if not triggered by workflow dispatch set to default
      id: updated_input
      run: |
        if [[ ${{ github.event_name }} != 'workflow_dispatch' ]]; then
          echo "This workflow was not triggered by workflow_dispatch"
          echo "VERSION_FLAG=false" >> "$GITHUB_OUTPUT"
        else
          echo "This workflow was triggered by workflow_dispatch"
          echo "VERSION_FLAG=${{ inputs.isMajorVersion }}" >> "$GITHUB_OUTPUT"
        fi     
  publis-release:
    runs-on: ubuntu-latest
    needs: setup-vars
    steps:
    - name: test
      run: |
        echo "${{ setup-vars.updated_input.outputs.VERSION_FLAG }}"
