

name: Mater Branch workflow

on:
  workflow_dispatch:
    inputs:
      var:
        description: 'Description for var'
        required: false
        default: 'false'
        
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  var-experiment:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Print Triggering Event
      run: |
          echo "Triggered by ${{ github.event_name }}"    
        
    - name: Print Run Command
      run: |
          echo "The input run command is: ${{ inputs.run_command }}"
      
